# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4

### Builder stage ###
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package and tsconfig
COPY package.json package-lock.json tsconfig.json ./
# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && \
    npm run build

### Production stage ###
FROM node:lts-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production

# Copy only production dependencies
COPY package.json package-lock.json ./
RUN npm ci --only=production

# Copy compiled dist from builder
COPY --from=builder /app/dist ./dist
# Add symlink for build folder to satisfy smithery config
RUN ln -s dist build

# Default command
CMD ["node", "build/index.js"]
